name: front_have_a_meal
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # 무료 애플 스타일 아이콘
  cupertino_icons: ^1.0.6

  # 시중에 있는 무료 아이콘 라이브러리
  font_awesome_flutter: ^10.7.0

  # 통신 라이브러리
  http: ^1.2.1

  # 스토리지 만드는 라이브러리
  flutter_secure_storage: ^9.0.0

  # 상태 관리 라이브러리
  provider: ^6.1.2

  # 라우터 페이지 관리 라이브러리
  go_router: ^13.2.2

  # 날짜, 단위 포맷 라이브러리
  intl: ^0.18.1

  # 한국어 적용 라이브러리
  flutter_localization: ^0.2.0

  # Gap 라이브러리
  gap: ^3.0.1

  # 아임포트 결제 관리 라이브러리
  iamport_flutter: ^0.10.18

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
